export const mockTransactions = [
  {
    id: "1",
    type: "pix_received",
    description: "PIX recebido de Carlos Souza",
    amount: 8200.0,
    recipient: "Carlos Souza",
    recipient_key: "carlos@email.com",
    status: "completed",
    category: "transfer",
    created_date: "2026-03-14T14:20:00Z",
  },
  {
    id: "2",
    type: "pix_sent",
    description: "PIX para João Silva",
    amount: -1250.0,
    recipient: "João Silva",
    recipient_key: "123.456.789-00",
    status: "completed",
    category: "transfer",
    created_date: "2026-03-13T10:30:00Z",
  },
  {
    id: "3",
    type: "investment",
    description: "Investimento Soja RWA",
    amount: -5000.0,
    recipient: "FeeAgro Soja Fund",
    recipient_key: null,
    status: "completed",
    category: "investment",
    created_date: "2026-03-13T09:00:00Z",
  },
  {
    id: "4",
    type: "pix_received",
    description: "PIX recebido de Maria Lima",
    amount: 3500.0,
    recipient: "Maria Lima",
    recipient_key: "(11) 99999-0000",
    status: "completed",
    category: "transfer",
    created_date: "2026-03-12T15:45:00Z",
  },
  {
    id: "5",
    type: "withdrawal",
    description: "Saque conta corrente",
    amount: -2000.0,
    recipient: "Banco do Brasil",
    recipient_key: null,
    status: "completed",
    category: "transfer",
    created_date: "2026-03-11T11:00:00Z",
  },
  {
    id: "6",
    type: "deposit",
    description: "Depósito via TED",
    amount: 15000.0,
    recipient: "Transferência TED",
    recipient_key: null,
    status: "completed",
    category: "salary",
    created_date: "2026-03-10T08:30:00Z",
  },
  {
    id: "7",
    type: "investment",
    description: "Investimento Milho RWA",
    amount: -3500.0,
    recipient: "FeeAgro Milho Fund",
    recipient_key: null,
    status: "pending",
    category: "investment",
    created_date: "2026-03-09T16:20:00Z",
  },
  {
    id: "8",
    type: "pix_sent",
    description: "PIX para Ana Costa",
    amount: -750.0,
    recipient: "Ana Costa",
    recipient_key: "ana@email.com",
    status: "completed",
    category: "transfer",
    created_date: "2026-03-08T13:15:00Z",
  },
];
